language: java
install: true
jdk:
  - openjdk11

stages:
  - name: build
  - name: release
    if: branch = master AND type = push

jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: release
      script: ./gradlew bintrayUpload --exclude-task test -Drelease=true -PbuildVariant=release -Dbintray.user=${BINTRAY_USER} -Dbintray.key=${BINTRAY_KEY} -Dbuild.number=${TRAVIS_BUILD_NUMBER}